export default [
  {
    id: 1,
    vase_num: "29",
    shape_name: "Neck-amphora",
    provence: "Geneva",
    year: "1986",
    dimensions: "Ht. 42-3",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-15-1.jpg",
    description:
      "(a) Orestes and Pylades at the tomb of Agamemnon, on the base of which Electra is kneeling, a phiale in her one hand and her r. on top of a hydria; above-busts of two Furies, (b) nude youth with strigil and stick between draped youth (A 1) and draped woman, each with spray Neck: (a) Siren, holding fillet and tambourine, [b) female head in profile to 1.",
  },
  {
    id: 2,
    vase_num: "11138",
    shape_name: "Hydria",
    provence: "Madrid",
    year: "n/s",
    dimensions: "Ht. 37",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-16-2.jpg",
    description:
      "Eros bending forward to 1., holding open wreath in both hands, between, to 1., standing draped woman with fillet in r., cista and wreath in 1. and, to r., draped w o m an holding mirror. Below the handles: 1., female head; r., head of youth (Hermes ?), wearing petasos.",
  },
  {
    id: 3,
    vase_num: "n/s",
    shape_name: "Bell-kraters",
    provence: "New York Market",
    year: "1985",
    dimensions: "Ht. 30, diam. 26-5",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-17-1.jpg",
    description:
      "Art of the ancient world IV, 1985, no. 129, ill. on p. 39. Woman with tambourine dancing to 1., (b) bearded silen capering to 1., with phiale.",
  },
  {
    id: 4,
    vase_num: "32113",
    shape_name: "Bell-kraters",
    provence: "Paestum",
    year: "1964",
    dimensions: "Ht. 38, diam. 35",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-18-1.jpg",
    description:
      "(a) White-haired phlyax standing in front of seated Dionysos, with r. hand raised, halfdraped maenad, (b) Bv + A2. Recomposed from many fragments, with a good deal missing.",
  },
  {
    Id: 5,
    vase_num: "22449",
    shape_name: "Olpe",
    provence: "Paestum",
    year: "1969",
    dimensions: "Ht. 25",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-41-2.jpg",
    description:
      "Seated half-draped Dionysos, young satyr bending forward in front of him. Cf. no. 16, from the same tomb.",
  },
  {
    Id: 6,
    vase_num: "1812",
    shape_name: "Bell-kraters",
    provence: "Pontecagnano",
    year: "1960",
    dimensions: "Ht. 30-5, diam. 28",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-20-1.jpg",
    description:
      "(a) Seated Dionysos with phiale of eggs and white wreath, satyr (with Pan horns) holding syrinx, skin over his 1. arm, [b) Al + A2, with cloak drawn up over his head.",
  },
  {
    Id: 7,
    vase_num: "82",
    shape_name: "Bell-kraters",
    provence: "Los Angeles",
    year: "1973",
    dimensions: "Ht. 36, diam. 36-7",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-22-1.jpg",
    description:
      "(a) Seated white-haired silen clasping skyphos with both hands, Dionysos with thyrsus in r. hand and drapery around 1. arm; to 1., duck, [b) Al + A2, with cloak drawn up over head, each with spray.",
  },
  {
    Id: 8,
    vase_num: "5434",
    shape_name: "Hydriai",
    provence: "Hillsborough",
    year: "n/s",
    dimensions: "Ht. 34-5",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-23-1.jpg",
    description:
      "Draped woman holding mirror, nude youth (Dionysos) with thyrsus in r. hand, egg in 1.,and drapery over both arms standing in front of seated Eros, holding phiale and fillet in 1. hand, fillet in r. Below the handles: female heads.",
  },
  {
    Id: 9,
    vase_num: "21206",
    shape_name: "Bell-kraters",
    provence: "Paestum",
    year: "1969",
    dimensions: "Ht. 30, diam. 29-5",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-25-3.jpg",
    description:
      "Pontrandolfo, Dial, di Arch. 1979/2, p. 37, fig. 8 (showing whole tomb), reproduced in I Lucani, pi. 20)(a) Dionysos with thyrsus and horn, draped woman with wreath in upraised 1. hand and fillet over 1. arm, [b) Air + A.",
  },
  {
    Id: 10,
    vase_num: "466",
    shape_name: "Hydriai",
    provence: "London",
    year: "n/s",
    dimensions: "Ht. 26",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-37-1.jpg",
    description:
      "Body: nude youth, with drapery over upraised r. arm, holding mirror in 1. hand, kneeling beside a laver, above which is a waterspout, from which water is dripping down. Lids: (i) large—phlyax actor, holding crooked stick and wearing cloak over a white tunic; (ii) head of youth in profile to 1.; (iii) head of w o m a n in profile to 1., with a similar head on the underside.",
  },
  {
    Id: 11,
    vase_num: "26607",
    shape_name: "Pelikai",
    provence: "Paestum",
    year: "1972",
    dimensions: "Ht. 29-5",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-39.jpg",
    description:
      "(a) Eros, with mirror in 1. hand, leaning against laver, standing draped woman, with mirror in 1. hand, (a) A31 + A2r, with stele between them.",
  },
  {
    Id: 12,
    vase_num: "40987",
    shape_name: "Lebetes gamikoi",
    provence: "Paestum",
    year: "1976",
    dimensions: "Ht. 25",
    author: "A. D. Trendall",
    publication: "The red Vases of Paestum",
    images: "../images/P-41-1.jpg",
    description:
      "(a) Seated half-draped woman, holding up mirror in 1., wreath in r. [b) Eros with wreath and phiale by altar.",
  },
];
